# Generated by Django 2.1.8 on 2019-05-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0002_lost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lost',
            old_name='body',
            new_name='bod2y',
        ),
        migrations.RenameField(
            model_name='lost',
            old_name='pub_date',
            new_name='pub_date2',
        ),
        migrations.RenameField(
            model_name='lost',
            old_name='title',
            new_name='title2',
        ),
    ]
