# Generated by Django 2.1.8 on 2019-05-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0004_auto_20190512_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost',
            name='writer2',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lost',
            name='pub_date2',
            field=models.DateTimeField(),
        ),
    ]
