# Generated by Django 2.1.8 on 2019-05-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0005_auto_20190512_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='fest',
            name='writer',
            field=models.CharField(default='잘못된 사용자', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lost',
            name='pub_date2',
            field=models.DateTimeField(verbose_name='data pub'),
        ),
    ]
