# Generated by Django 2.1.8 on 2019-05-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0006_auto_20190512_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sword', models.CharField(max_length=10)),
            ],
        ),
    ]
