# Generated by Django 2.1.8 on 2019-05-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0007_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Password',
            new_name='Pass',
        ),
    ]
