# Generated by Django 2.1.8 on 2019-05-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0008_auto_20190512_1828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pass',
        ),
        migrations.AddField(
            model_name='fest',
            name='password',
            field=models.CharField(default='asd123', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lost',
            name='password2',
            field=models.CharField(default='asd123', max_length=20),
            preserve_default=False,
        ),
    ]
